services:
  postgres:
    image: postgres:18-alpine3.23
    container_name: localproject_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: local_project_redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: