version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  postgre_data: 
  redis-data:
  kafka-data:

services:
  app:
    image: ${IMAGE_NAME}
    container_name: app-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER_APP};Password=${DB_PASSWORD_APP};Maximum Pool Size=${DB_MAX_POOL_SIZE};Minimum Pool Size=1;Timeout=15;
      - ConnectionStrings__Redis=redis-stack:6379,password=${REDIS_PASSWORD}
      - Kafka__BootstrapServers=kafka:29092
      - Jwt__PublicKeyPath=${JWT_PUBLIC_KEY_CONTAINER_PATH}
      - Jwt__PrivateKeyPath=${JWT_PRIVATE_KEY_CONTAINER_PATH}
    depends_on:
      - db
      - redis-stack
      - kafka
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ${JWT_PUBLIC_KEY_HOST_PATH}:${JWT_PUBLIC_KEY_CONTAINER_PATH}:ro
      - ${JWT_PRIVATE_KEY_HOST_PATH}:${JWT_PRIVATE_KEY_CONTAINER_PATH}:ro
      
  analytcs:
    image: ${ANALYTICS_IMAGE_NAME}
    container_name: analytcs-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER_APP};Password=${DB_PASSWORD_APP};Maximum Pool Size=${DB_MAX_POOL_SIZE};Minimum Pool Size=1;Timeout=15;
      - ConnectionStrings__Redis=redis-stack:6379,password=${REDIS_PASSWORD}
      - Kafka__BootstrapServers=kafka:29092
      - Jwt__PublicKeyPath=${JWT_PUBLIC_KEY_CONTAINER_PATH}
    depends_on:
        - db
        - redis-stack
        - kafka
    networks:
        - app-network
        
    ports:
        - "4545:4545"
    volumes:
      - ${JWT_PUBLIC_KEY_HOST_PATH}:${JWT_PUBLIC_KEY_CONTAINER_PATH}:ro
  
  db:
    image: postgres:18-alpine3.23
    container_name: db-container
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_APP}
      - POSTGRES_PASSWORD=${DB_PASSWORD_APP}
      - POSTGRES_DB=${DB_NAME}
    command: postgres -c max_connections=30 -c shared_buffers=256MB
    ports:
      - "${DB_OUT_PORT}:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-container
    restart: always
    command: redis-stack-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network 
      
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data
      
    networks:
      - app-network

