version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  postgre_data: 
  redis-data:

services:
  app:
    image: ${IMAGE_NAME}
    container_name: app-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER_APP};Password=${DB_PASSWORD_APP};Maximum Pool Size=${DB_MAX_POOL_SIZE};Minimum Pool Size=1;Timeout=15;
      - ConnectionStrings__Redis=redis-stack:6379,password=${REDIS_PASSWORD}
      - Jwt__Key=${JWT_KEY}
    depends_on:
      - db
      - redis-stack
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:18-alpine3.23
    container_name: db-container
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_APP}
      - POSTGRES_PASSWORD=${DB_PASSWORD_APP}
      - POSTGRES_DB=${DB_NAME}
    command: postgres -c max_connections=30 -c shared_buffers=256MB
    ports:
      - "${DB_OUT_PORT}:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-container
    restart: always
    command: redis-stack-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network 
