name: EF Migration and CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore
        
      - name: Create EF Migration Bundle
        env:
          Jwt__Key: "ThisIsATemporaryKeyForBuildPurposesOnly32Chars!!"
          ConnectionStrings__DefaultConnection: "Host=localhost;Database=dummy"
        run: |
            dotnet tool install --global dotnet-ef
            dotnet ef migrations bundle \
              --project Fitness-Tracker-Infrastructure/Fitness-Tracker-Infrastructure.csproj \
              --startup-project Fitness-Tracker/Fitness-Tracker.csproj \
              --output efbundle \
              --self-contained
            
      - name: Run Bundle
        run: |
            # Копируем конфиг из папки проекта в корень к бандлу
            cp Fitness-Tracker/appsettings.json .
            
            chmod +x ./efbundle
            # Передаем строку подключения из секретов
            ./efbundle --connection "${{ secrets.DB_CONNECTION_STRING }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/myprojects:latest

      - name: Update Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PATH_TO_DOCKER_COMPOSE }}
            docker compose pull
            docker compose up -d --remove-orphans
        